pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=github-actions[bot]
    actions:
      assign:
        users: [NomadBlacky]
      label:
        add: [dependency]
  - name: merge scala-steward's PRs
    conditions:
      - author=github-actions[bot]
      - "status-success=test (8)"
      - "status-success=test (11)"
    actions:
      merge:
        method: squash
